CREATE TABLE stamp_record (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    user_id                     NUMBER NOT NULL,
    check_in_in_milliseconds    BIGINT,
    check_out_in_milliseconds   BIGINT
);

CREATE TABLE stamp_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    user_name   VARCHAR(255)
);